# Generated by Django 6.0.1 on 2026-02-19 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TunerApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("business_name", models.CharField(max_length=255)),
                ("experience_summary", models.TextField()),
                ("website_url", models.URLField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("reviewer_notes", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tuner_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TunerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("business_name", models.CharField(max_length=255)),
                ("logo_url", models.URLField(blank=True, null=True)),
                ("slug", models.SlugField(unique=True)),
                (
                    "verification_level",
                    models.CharField(
                        choices=[
                            ("COMMUNITY", "Community Tuner"),
                            ("VERIFIED", "Verified Tuner"),
                            ("PRO", "Pro Tuner"),
                            ("MASTER", "Master Tuner"),
                        ],
                        default="COMMUNITY",
                        max_length=20,
                    ),
                ),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("NEW", "New (Manual Review Required)"),
                            ("TRUSTED", "Trusted (Auto-Approve Enabled)"),
                        ],
                        default="NEW",
                        max_length=20,
                    ),
                ),
                ("is_suspended", models.BooleanField(default=False)),
                ("total_downloads", models.PositiveIntegerField(default=0)),
                (
                    "average_rating",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tuner_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
