-- Supabase Schema Definition for RevSync
-- Generated based on Django Models

-- Users & Profiles
CREATE TABLE users_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    password VARCHAR(128) NOT NULL,
    last_login TIMESTAMP WITH TIME ZONE,
    is_superuser BOOLEAN NOT NULL,
    username VARCHAR(150) NOT NULL UNIQUE,
    first_name VARCHAR(150) NOT NULL,
    last_name VARCHAR(150) NOT NULL,
    email VARCHAR(254) NOT NULL UNIQUE,
    is_staff BOOLEAN NOT NULL,
    is_active BOOLEAN NOT NULL,
    date_joined TIMESTAMP WITH TIME ZONE NOT NULL,
    role VARCHAR(20) NOT NULL,
    is_verified BOOLEAN NOT NULL
);

CREATE TABLE users_userprofile (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    bio TEXT NOT NULL,
    country VARCHAR(100) NOT NULL,
    photo_url VARCHAR(200),
    experience_level VARCHAR(50) NOT NULL,
    riding_style VARCHAR(50) NOT NULL,
    last_active TIMESTAMP WITH TIME ZONE NOT NULL,
    user_id BIGINT NOT NULL UNIQUE REFERENCES users_user(id)
);

-- Tuners
CREATE TABLE tuners_tunerprofile (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    business_name VARCHAR(255) NOT NULL,
    logo_url VARCHAR(200),
    specializations JSONB NOT NULL,
    years_experience INTEGER NOT NULL CHECK (years_experience >= 0),
    verification_level VARCHAR(20) NOT NULL,
    is_verified_business BOOLEAN NOT NULL,
    total_downloads INTEGER NOT NULL CHECK (total_downloads >= 0),
    average_rating NUMERIC(3, 2) NOT NULL,
    tunes_published_count INTEGER NOT NULL CHECK (tunes_published_count >= 0),
    quality_score INTEGER NOT NULL CHECK (quality_score >= 0),
    user_id BIGINT NOT NULL UNIQUE REFERENCES users_user(id)
);

-- Garage
CREATE TABLE garage_vehicle (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    name VARCHAR(100) NOT NULL,
    vehicle_type VARCHAR(10) NOT NULL,
    make VARCHAR(100) NOT NULL,
    model VARCHAR(100) NOT NULL,
    year INTEGER NOT NULL CHECK (year >= 0),
    vin VARCHAR(17),
    ecu_id VARCHAR(100) NOT NULL,
    ecu_software_version VARCHAR(100) NOT NULL,
    modifications JSONB NOT NULL,
    photo_url VARCHAR(200),
    user_id BIGINT NOT NULL REFERENCES users_user(id)
);

-- Marketplace
CREATE TABLE marketplace_tune (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    vehicle_make VARCHAR(100) NOT NULL,
    vehicle_model VARCHAR(100) NOT NULL,
    vehicle_year_start INTEGER NOT NULL CHECK (vehicle_year_start >= 0),
    vehicle_year_end INTEGER NOT NULL CHECK (vehicle_year_end >= 0),
    ecu_compatibility JSONB NOT NULL,
    stage SMALLINT NOT NULL CHECK (stage >= 0),
    horsepower_gain NUMERIC(5, 1),
    torque_gain NUMERIC(5, 1),
    dyno_chart_url VARCHAR(200),
    file_url VARCHAR(200) NOT NULL,
    file_size_kb INTEGER NOT NULL CHECK (file_size_kb >= 0),
    price NUMERIC(8, 2) NOT NULL,
    is_active BOOLEAN NOT NULL,
    safety_rating SMALLINT NOT NULL CHECK (safety_rating >= 0),
    creator_id BIGINT NOT NULL REFERENCES tuners_tunerprofile(id)
);

CREATE TABLE marketplace_purchase (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    price_paid NUMERIC(8, 2) NOT NULL,
    transaction_id VARCHAR(100) NOT NULL UNIQUE,
    tune_id BIGINT NOT NULL REFERENCES marketplace_tune(id),
    user_id BIGINT NOT NULL REFERENCES users_user(id)
);
