# Generated by Django 5.2.8 on 2025-11-20 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("garage", "0003_ecubackup_deleted_at_vehicle_deleted_at"),
        ("marketplace", "0002_tune_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SafetyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "risk_score",
                    models.PositiveSmallIntegerField(
                        help_text="0-100, higher is riskier"
                    ),
                ),
                ("status", models.CharField(default="SAFE", max_length=20)),
                ("input_data", models.JSONField(default=dict)),
                ("analysis_result", models.JSONField(default=dict)),
                ("recommendations", models.JSONField(default=list)),
                (
                    "tune",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="marketplace.tune",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="safety_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="garage.vehicle",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
