# Generated by Django 6.0.1 on 2026-02-03 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("marketplace", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SafetyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "risk_score",
                    models.PositiveSmallIntegerField(
                        help_text="0-100, higher is riskier"
                    ),
                ),
                ("status", models.CharField(default="SAFE", max_length=20)),
                ("input_data", models.JSONField(default=dict)),
                ("analysis_result", models.JSONField(default=dict)),
                ("recommendations", models.JSONField(default=list)),
                (
                    "listing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="marketplace.tunelisting",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
