# Generated by Django 6.0.1 on 2026-02-03 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EcuBackup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "storage_key",
                    models.CharField(
                        help_text="Path in storage bucket", max_length=255
                    ),
                ),
                (
                    "checksum",
                    models.CharField(help_text="SHA-256 checksum", max_length=64),
                ),
                ("file_size_kb", models.PositiveIntegerField()),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FlashJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("FLASHING", "Flashing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "progress",
                    models.PositiveSmallIntegerField(default=0, help_text="0-100"),
                ),
                ("logs", models.JSONField(blank=True, default=list)),
                ("error_message", models.TextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Nickname for the vehicle", max_length=100
                    ),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[("BIKE", "Motorcycle"), ("CAR", "Car")],
                        default="BIKE",
                        max_length=10,
                    ),
                ),
                ("make", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                ("year", models.PositiveIntegerField()),
                ("vin", models.CharField(blank=True, max_length=17, null=True)),
                (
                    "ecu_type",
                    models.CharField(
                        blank=True, help_text="e.g. Bosch, Keihin", max_length=50
                    ),
                ),
                (
                    "ecu_id",
                    models.CharField(
                        blank=True, help_text="ECU Hardware ID", max_length=100
                    ),
                ),
                ("ecu_software_version", models.CharField(blank=True, max_length=100)),
                (
                    "modifications",
                    models.JSONField(
                        blank=True, default=list, help_text="List of installed mods"
                    ),
                ),
                ("photo_url", models.URLField(blank=True, null=True)),
                (
                    "public_visibility",
                    models.BooleanField(
                        default=False, help_text="Visible to other users?"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VehicleDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[("BIKE", "Motorcycle"), ("CAR", "Car")],
                        default="BIKE",
                        max_length=10,
                    ),
                ),
                ("make", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                ("year", models.PositiveIntegerField()),
                ("stock_hp", models.FloatField(default=0)),
                ("stock_torque", models.FloatField(default=0)),
            ],
            options={
                "ordering": ["make", "model", "-year"],
            },
        ),
    ]
