# Generated by Django 5.2.8 on 2025-11-20 02:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Nickname for the vehicle", max_length=100
                    ),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[("BIKE", "Motorcycle"), ("CAR", "Car")],
                        default="BIKE",
                        max_length=10,
                    ),
                ),
                ("make", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                ("year", models.PositiveIntegerField()),
                ("vin", models.CharField(blank=True, max_length=17, null=True)),
                (
                    "ecu_type",
                    models.CharField(
                        blank=True, help_text="e.g. Bosch, Keihin", max_length=50
                    ),
                ),
                (
                    "ecu_id",
                    models.CharField(
                        blank=True, help_text="ECU Hardware ID", max_length=100
                    ),
                ),
                ("ecu_software_version", models.CharField(blank=True, max_length=100)),
                (
                    "modifications",
                    models.JSONField(
                        blank=True, default=list, help_text="List of installed mods"
                    ),
                ),
                ("photo_url", models.URLField(blank=True, null=True)),
                (
                    "public_visibility",
                    models.BooleanField(
                        default=False, help_text="Visible to other users?"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
