# Generated by Django 5.2.8 on 2025-11-20 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("garage", "0002_ecubackup_flashjob"),
    ]

    operations = [
        migrations.AddField(
            model_name="ecubackup",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
