# Generated by Django 6.0.1 on 2026-02-10 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("garage", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="flashjob",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="flashjob",
            name="backup",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="flash_jobs",
                to="garage.ecubackup",
            ),
        ),
        migrations.AddField(
            model_name="flashjob",
            name="chunks_sent",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="flashjob",
            name="connection_type",
            field=models.CharField(
                choices=[("BLE", "Bluetooth LE"), ("USB", "USB Serial")],
                default="BLE",
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="flashjob",
            name="device_id",
            field=models.CharField(
                blank=True, help_text="BLE device ID or USB port", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="flashjob",
            name="ecu_read_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Data read from ECU during identify/backup (HW ID, FW version, etc.)",
            ),
        ),
        migrations.AddField(
            model_name="flashjob",
            name="error_code",
            field=models.CharField(
                blank=True, help_text="Machine-readable error code", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="flashjob",
            name="flash_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="flashjob",
            name="flash_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="flashjob",
            name="total_chunks",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="flashjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("CREATED", "Created"),
                    ("PRE_CHECK", "Pre-flight Check"),
                    ("BACKING_UP", "Backing Up ECU"),
                    ("FLASHING", "Flashing"),
                    ("VERIFYING", "Verifying Flash"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                    ("RECOVERING", "Recovering from Backup"),
                    ("ABORTED", "Aborted by User"),
                ],
                default="CREATED",
                max_length=20,
            ),
        ),
    ]
