# Generated by Django 5.2.8 on 2025-11-21 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("garage", "0003_ecubackup_deleted_at_vehicle_deleted_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="VehicleDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[("BIKE", "Motorcycle"), ("CAR", "Car")],
                        default="BIKE",
                        max_length=10,
                    ),
                ),
                ("make", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                ("year", models.PositiveIntegerField()),
                ("stock_hp", models.FloatField(default=0)),
                ("stock_torque", models.FloatField(default=0)),
            ],
            options={
                "ordering": ["make", "model", "-year"],
                "unique_together": {("make", "model", "year")},
            },
        ),
    ]
