# Generated by Django 6.0.1 on 2026-02-10 17:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0002_initial"),
        ("payments", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paymenttransaction",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="dispute_id",
            field=models.CharField(
                blank=True,
                help_text="Stripe Dispute ID (dp_...) if disputed",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="dispute_reason",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="disputed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="refund_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Amount refunded (cents → dollars)",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="refund_id",
            field=models.CharField(
                blank=True,
                help_text="Stripe Refund ID (re_...) if refunded",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="refund_reason",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="refunded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="stripe_charge_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Stripe Charge ID (ch_...) — set on success",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="user_agent",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="webhook_event_id",
            field=models.CharField(
                blank=True,
                help_text="Stripe Event ID that last updated this record (evt_...)",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("succeeded", "Succeeded"),
                    ("failed", "Failed"),
                    ("refunded", "Refunded"),
                    ("disputed", "Disputed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="stripe_payment_intent_id",
            field=models.CharField(
                db_index=True,
                help_text="Stripe PaymentIntent ID (pi_...)",
                max_length=255,
                unique=True,
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(
                fields=["user", "status"], name="payments_pa_user_id_92d873_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(
                fields=["stripe_payment_intent_id"],
                name="payments_pa_stripe__3365e3_idx",
            ),
        ),
    ]
