# Generated by Django 6.0.1 on 2026-02-03 02:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PurchaseEntitlement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("transaction_id", models.CharField(max_length=100)),
                ("is_revoked", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="TuneListing",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField()),
                ("vehicle_make", models.CharField(db_index=True, max_length=100)),
                ("vehicle_model", models.CharField(db_index=True, max_length=100)),
                ("vehicle_year_start", models.PositiveSmallIntegerField()),
                ("vehicle_year_end", models.PositiveSmallIntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TuneVersion",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version_number", models.CharField(max_length=50)),
                ("changelog", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("UPLOADED", "Uploaded"),
                            ("VALIDATING", "Validating"),
                            ("FAILED", "Validation Failed"),
                            ("READY_FOR_REVIEW", "Ready for Review"),
                            ("APPROVED", "Approved"),
                            ("PUBLISHED", "Published"),
                            ("SUSPENDED", "Suspended"),
                        ],
                        default="DRAFT",
                        max_length=50,
                    ),
                ),
                ("quarantine_path", models.CharField(blank=True, max_length=500)),
                ("validated_path", models.CharField(blank=True, max_length=500)),
                (
                    "file_hash_sha256",
                    models.CharField(
                        blank=True, help_text="SHA256 of the tune.bin", max_length=64
                    ),
                ),
                ("manifest_hash_sha256", models.CharField(blank=True, max_length=64)),
                (
                    "signature_base64",
                    models.TextField(
                        blank=True, help_text="Ed25519 Signature by RevSync"
                    ),
                ),
                ("signed_at", models.DateTimeField(blank=True, null=True)),
                ("manifest_data", models.JSONField(blank=True, default=dict)),
                ("file_size_bytes", models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="ValidationReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_passed", models.BooleanField(default=False)),
                ("results", models.JSONField(default=dict)),
                ("blockers", models.JSONField(default=list)),
                ("warnings", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
