# Generated by Django 6.0.1 on 2026-02-03 02:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("marketplace", "0001_initial"),
        ("tuners", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseentitlement",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entitlements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tunelisting",
            name="tuner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listings",
                to="tuners.tunerprofile",
            ),
        ),
        migrations.AddField(
            model_name="purchaseentitlement",
            name="listing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entitlements",
                to="marketplace.tunelisting",
            ),
        ),
        migrations.AddField(
            model_name="tuneversion",
            name="listing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versions",
                to="marketplace.tunelisting",
            ),
        ),
        migrations.AddField(
            model_name="validationreport",
            name="version",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="validation_report",
                to="marketplace.tuneversion",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="purchaseentitlement",
            unique_together={("user", "listing")},
        ),
        migrations.AlterUniqueTogether(
            name="tuneversion",
            unique_together={("listing", "version_number")},
        ),
    ]
