# Generated by Django 5.2.8 on 2025-11-24 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_follow"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_garage_public",
            field=models.BooleanField(
                default=True, help_text="Allow others to see your garage."
            ),
        ),
    ]
