# Generated by Django 5.2.8 on 2026-02-03 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_userprofile_is_garage_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="is_moderator",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="is_tuner",
            field=models.BooleanField(
                default=False, help_text="Approved tuner/publisher"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="tuner_tier",
            field=models.CharField(
                choices=[("NEW", "New"), ("TRUSTED", "Trusted")],
                default="NEW",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="supabase_user_id",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("RIDER", "Rider"),
                    ("TUNER", "Tuner"),
                    ("CREATOR", "Creator"),
                    ("ADMIN", "Admin"),
                ],
                default="RIDER",
                help_text="Legacy role; flag-based access is authoritative.",
                max_length=20,
            ),
        ),
    ]
